export const QUESTIONS = {
  phone: [
    "Hey! 👋 What will you mainly use this phone for? (e.g. gaming, photography, social media, work, everyday use)",
    "Nice! Any must-have features? (e.g. great camera, long battery, compact size, 5G, fast charging)",
    "Almost there! Do you prefer any brand? Or are you open to all brands?",
  ],
  laptop: [
    "Hey! 👋 What will you mainly use this laptop for? (e.g. gaming, video editing, studying, programming, office work)",
    "Great! Any must-have features? (e.g. lightweight, long battery, powerful GPU, large screen, fast SSD)",
    "Almost there! Do you prefer Windows or macOS? Or no preference?",
  ]
}

export const DEVICES = {
  phone: [
    // Budget phones under $300
    { id:1, name:"Samsung Galaxy A16 5G", price:199, match:70, emoji:"📱", specs:{Display:"6.7\" AMOLED 90Hz", Processor:"Exynos 1330", RAM:"4GB", Storage:"128GB", Camera:"50MP triple", Battery:"5000mAh", OS:"Android 14", "5G":"Yes"}, why:"Most affordable 5G Samsung with 6 years of security updates. Great AMOLED display for the price.", tradeoff:"Only 4GB RAM feels slow multitasking. Processor is entry-level.", links:[["Samsung","https://samsung.com"],["Amazon","https://amazon.com/s?k=Samsung+Galaxy+A16+5G"]]},
    { id:2, name:"Motorola Moto G Power 5G 2024", price:249, match:74, emoji:"📱", specs:{Display:"6.7\" IPS LCD 120Hz", Processor:"Snapdragon 4 Gen 2", RAM:"8GB", Storage:"256GB", Camera:"50MP dual", Battery:"5000mAh", OS:"Android 14", "5G":"Yes"}, why:"Best overall budget phone. Wireless charging, NFC, clean software, and great battery at an unbeatable price.", tradeoff:"LCD display not as vibrant as OLED. Camera inconsistent indoors.", links:[["Motorola","https://motorola.com"],["Amazon","https://amazon.com/s?k=Motorola+Moto+G+Power+5G+2024"]]},
    { id:3, name:"OnePlus Nord N30 5G", price:299, match:75, emoji:"📱", specs:{Display:"6.72\" LCD 120Hz", Processor:"Snapdragon 695", RAM:"8GB", Storage:"128GB", Camera:"108MP dual", Battery:"5000mAh", OS:"Android 13", "5G":"Yes"}, why:"Best fast charging budget phone. 50W charging fills up in 45 minutes. 108MP camera impressive for the price.", tradeoff:"Only one major OS update promised. LCD display.", links:[["OnePlus","https://oneplus.com"],["Amazon","https://amazon.com/s?k=OnePlus+Nord+N30+5G"]]},
    { id:4, name:"CMF Phone 2 Pro", price:279, match:76, emoji:"📱", specs:{Display:"6.77\" AMOLED 120Hz", Processor:"Snapdragon 7s Gen 2", RAM:"8GB", Storage:"256GB", Camera:"50MP triple", Battery:"5000mAh", OS:"Android 15", "5G":"Yes"}, why:"Most unique budget phone. Modular design, 6 years of security updates, and clean Nothing OS software.", tradeoff:"No wireless charging. Accessories add extra cost.", links:[["Nothing","https://nothing.tech"],["Amazon","https://amazon.com/s?k=CMF+Phone+2+Pro"]]},
    { id:5, name:"Motorola Edge 2024", price:249, match:77, emoji:"📱", specs:{Display:"6.6\" pOLED 144Hz", Processor:"Snapdragon 7s Gen 2", RAM:"8GB", Storage:"256GB", Camera:"50MP dual", Battery:"4500mAh", OS:"Android 14", "5G":"Yes"}, why:"Most premium-feeling budget phone. Curved OLED display, IP68 water resistance, and wireless charging under $250.", tradeoff:"No headphone jack. Limited software update support.", links:[["Motorola","https://motorola.com"],["Amazon","https://amazon.com/s?k=Motorola+Edge+2024"]]},
    { id:6, name:"Samsung Galaxy A26 5G", price:299, match:75, emoji:"📱", specs:{Display:"6.6\" AMOLED 120Hz", Processor:"Exynos 1580", RAM:"8GB", Storage:"128GB", Camera:"50MP triple", Battery:"5000mAh", OS:"Android 15", "5G":"Yes"}, why:"Best Samsung under $300. Beautiful AMOLED display and reliable Samsung software with long update support.", tradeoff:"Exynos chip slower than Snapdragon. No wireless charging.", links:[["Samsung","https://samsung.com"],["Amazon","https://amazon.com/s?k=Samsung+Galaxy+A26+5G"]]},
    { id:7, name:"Poco X6 Pro 5G", price:274, match:78, emoji:"📱", specs:{Display:"6.67\" AMOLED 120Hz", Processor:"Dimensity 8300 Ultra", RAM:"12GB", Storage:"512GB", Camera:"64MP dual", Battery:"5000mAh", OS:"Android 14", "5G":"Yes"}, why:"Best performance under $300. Dimensity 8300 Ultra is a near-flagship chip with 12GB RAM and 512GB storage.", tradeoff:"MIUI has bloatware. Limited global software support.", links:[["Poco","https://poco.net"],["Amazon","https://amazon.com/s?k=Poco+X6+Pro"]]},
    { id:8, name:"Moto G Stylus 5G 2024", price:279, match:72, emoji:"📱", specs:{Display:"6.7\" IPS LCD 120Hz", Processor:"Snapdragon 6 Gen 1", RAM:"8GB", Storage:"256GB", Camera:"50MP dual + stylus", Battery:"5000mAh", OS:"Android 14", "5G":"Yes"}, why:"Only budget phone with a built-in stylus. Great for note-taking, sketching, and productivity tasks.", tradeoff:"LCD display. Stylus less capable than Samsung S Pen.", links:[["Motorola","https://motorola.com"],["Amazon","https://amazon.com/s?k=Moto+G+Stylus+5G+2024"]]},

    // Mid-range phones $300-$700
    { id:9, name:"Google Pixel 9a", price:499, match:89, emoji:"📱", specs:{Display:"6.3\" OLED 120Hz", Processor:"Google Tensor G4", RAM:"8GB", Storage:"128GB", Camera:"48MP dual", Battery:"5100mAh", OS:"Android 15", "5G":"Yes"}, why:"Best value phone of 2025. Flagship AI camera features, massive battery, and 7 years of guaranteed updates.", tradeoff:"No telephoto lens. Tensor chip not as fast as Snapdragon.", links:[["Google Store","https://store.google.com/product/pixel_9a"],["Amazon","https://amazon.com/s?k=Google+Pixel+9a"]]},
    { id:10, name:"Samsung Galaxy A56 5G", price:449, match:78, emoji:"📱", specs:{Display:"6.6\" AMOLED 120Hz", Processor:"Exynos 1580", RAM:"8GB", Storage:"128GB", Camera:"50MP triple", Battery:"5000mAh", OS:"Android 15", "5G":"Yes"}, why:"Best mid-ranger from Samsung. Great display, solid cameras, and 4 years of OS updates.", tradeoff:"Exynos chip slower than Snapdragon rivals. No wireless charging.", links:[["Samsung","https://samsung.com"],["Amazon","https://amazon.com/s?k=Samsung+Galaxy+A56"]]},
    { id:11, name:"Nothing Phone 3a Pro", price:459, match:79, emoji:"📱", specs:{Display:"6.77\" AMOLED 120Hz", Processor:"Snapdragon 7s Gen 3", RAM:"8GB", Storage:"256GB", Camera:"50MP triple", Battery:"5000mAh", OS:"Android 15", "5G":"Yes"}, why:"Most unique design on the market with Glyph interface. Clean software and versatile triple camera system.", tradeoff:"No wireless charging. Gaming performance is mid-range.", links:[["Nothing","https://nothing.tech"],["Amazon","https://amazon.com/s?k=Nothing+Phone+3a+Pro"]]},
    { id:12, name:"Motorola Edge 50 Pro", price:399, match:76, emoji:"📱", specs:{Display:"6.7\" pOLED 144Hz", Processor:"Snapdragon 7s Gen 2", RAM:"12GB", Storage:"256GB", Camera:"50MP triple", Battery:"4500mAh", OS:"Android 14", "5G":"Yes"}, why:"Best display in its price range with 144Hz pOLED. 68W fast charging and clean near-stock Android experience.", tradeoff:"Mid-range chip. Camera consistency could be better.", links:[["Motorola","https://motorola.com"],["Amazon","https://amazon.com/s?k=Motorola+Edge+50+Pro"]]},
    { id:13, name:"Xiaomi Redmi Note 13 Pro", price:329, match:74, emoji:"📱", specs:{Display:"6.67\" AMOLED 120Hz", Processor:"Snapdragon 7s Gen 2", RAM:"8GB", Storage:"256GB", Camera:"200MP triple", Battery:"5100mAh", OS:"Android 14", "5G":"Yes"}, why:"Best camera for price. 200MP main sensor with AMOLED display and huge battery is incredible value.", tradeoff:"MIUI has ads and bloatware. Limited software update support.", links:[["Xiaomi","https://xiaomi.com"],["Amazon","https://amazon.com/s?k=Xiaomi+Redmi+Note+13+Pro"]]},
    { id:14, name:"OnePlus 13R", price:499, match:80, emoji:"📱", specs:{Display:"6.78\" AMOLED 120Hz", Processor:"Snapdragon 8 Gen 2", RAM:"16GB", Storage:"256GB", Camera:"50MP triple", Battery:"5500mAh", OS:"Android 15", "5G":"Yes"}, why:"Flagship chip at mid-range price. Snapdragon 8 Gen 2 with 16GB RAM handles anything including heavy gaming.", tradeoff:"Camera not as refined as Samsung or Google. OxygenOS bloated.", links:[["OnePlus","https://oneplus.com"],["Amazon","https://amazon.com/s?k=OnePlus+13R"]]},
    { id:15, name:"iPhone 16e", price:599, match:82, emoji:"📱", specs:{Display:"6.1\" OLED", Processor:"A18", RAM:"8GB", Storage:"128GB", Camera:"48MP single", Battery:"3877mAh", OS:"iOS 18", "5G":"Yes"}, why:"Most affordable iPhone with Apple Intelligence and A18 chip. Best choice for entering Apple ecosystem.", tradeoff:"Only one rear camera. No MagSafe wireless charging.", links:[["Apple","https://apple.com/iphone-16e"],["Amazon","https://amazon.com/s?k=iPhone+16e"]]},
    { id:16, name:"Samsung Galaxy S25 FE", price:649, match:85, emoji:"📱", specs:{Display:"6.7\" AMOLED 120Hz", Processor:"Snapdragon 8 Gen 3", RAM:"8GB", Storage:"128GB", Camera:"50MP triple", Battery:"4900mAh", OS:"Android 15", "5G":"Yes"}, why:"Best phone under $700. Premium hardware almost identical to the S25 with 7 years of Samsung software updates.", tradeoff:"Slightly older chip than S25. No S Pen.", links:[["Samsung","https://samsung.com"],["Amazon","https://amazon.com/s?k=Samsung+Galaxy+S25+FE"]]},
    { id:17, name:"Google Pixel 8a", price:399, match:82, emoji:"📱", specs:{Display:"6.1\" OLED 120Hz", Processor:"Google Tensor G3", RAM:"8GB", Storage:"128GB", Camera:"64MP dual", Battery:"4492mAh", OS:"Android 14", "5G":"Yes"}, why:"Excellent AI camera and 7 years of updates at a discounted price now that Pixel 9a is out.", tradeoff:"Tensor G3 runs warm. No telephoto lens.", links:[["Google Store","https://store.google.com/product/pixel_8a"],["Amazon","https://amazon.com/s?k=Google+Pixel+8a"]]},
    { id:18, name:"OnePlus 12", price:599, match:83, emoji:"📱", specs:{Display:"6.82\" LTPO AMOLED 120Hz", Processor:"Snapdragon 8 Gen 3", RAM:"12GB", Storage:"256GB", Camera:"50MP Hasselblad triple", Battery:"5400mAh", OS:"Android 15", "5G":"Yes"}, why:"Best battery life in its class. 100W charging fills in 26 minutes. Flagship chip for less than Samsung.", tradeoff:"Camera software less refined. Resale value lower than Samsung/Apple.", links:[["OnePlus","https://oneplus.com"],["Amazon","https://amazon.com/s?k=OnePlus+12"]]},

    // Flagship phones $700+
    { id:19, name:"Samsung Galaxy S25 Ultra", price:1299, match:97, emoji:"📱", specs:{Display:"6.9\" AMOLED 120Hz", Processor:"Snapdragon 8 Elite", RAM:"12GB", Storage:"256GB", Camera:"200MP quad", Battery:"5000mAh", OS:"Android 15", "5G":"Yes"}, why:"The ultimate Android phone. Best-in-class display, S Pen included, 200MP camera, and Snapdragon 8 Elite.", tradeoff:"Very expensive. Large and heavy. S Pen niche for most users.", links:[["Samsung","https://samsung.com"],["Amazon","https://amazon.com/s?k=Samsung+Galaxy+S25+Ultra"]]},
    { id:20, name:"iPhone 17 Pro", price:999, match:95, emoji:"📱", specs:{Display:"6.3\" Super Retina XDR 120Hz", Processor:"A19 Pro", RAM:"8GB", Storage:"256GB", Camera:"48MP triple", Battery:"4685mAh", OS:"iOS 18", "5G":"Yes"}, why:"Apple's best iPhone ever. Best video recording on any phone, titanium build, and A19 Pro chip.", tradeoff:"Very expensive. Limited customization vs Android.", links:[["Apple","https://apple.com/iphone-17-pro"],["Amazon","https://amazon.com/s?k=iPhone+17+Pro"]]},
    { id:21, name:"Samsung Galaxy S25", price:799, match:92, emoji:"📱", specs:{Display:"6.2\" AMOLED 120Hz", Processor:"Snapdragon 8 Elite", RAM:"12GB", Storage:"128GB", Camera:"50MP triple", Battery:"4000mAh", OS:"Android 15", "5G":"Yes"}, why:"Compact flagship power. Snapdragon 8 Elite is blazingly fast with outstanding camera quality.", tradeoff:"Battery life could be better. No charger in box.", links:[["Samsung","https://samsung.com"],["Amazon","https://amazon.com/s?k=Samsung+Galaxy+S25"]]},
    { id:22, name:"iPhone 17", price:829, match:90, emoji:"📱", specs:{Display:"6.1\" Super Retina XDR 120Hz", Processor:"A18", RAM:"8GB", Storage:"128GB", Camera:"48MP dual", Battery:"3877mAh", OS:"iOS 18", "5G":"Yes"}, why:"Best all-rounder iPhone. Great cameras, smooth performance, and most Pro features at a lower price.", tradeoff:"No telephoto lens. Smaller battery than Android rivals.", links:[["Apple","https://apple.com/iphone-17"],["Amazon","https://amazon.com/s?k=iPhone+17"]]},
    { id:23, name:"Google Pixel 9 Pro", price:999, match:91, emoji:"📱", specs:{Display:"6.3\" OLED 120Hz", Processor:"Google Tensor G4", RAM:"16GB", Storage:"256GB", Camera:"50MP triple", Battery:"4700mAh", OS:"Android 15", "5G":"Yes"}, why:"Best AI camera phone. Google's computational photography leads the industry with 7 years of guaranteed updates.", tradeoff:"Tensor chip runs warm. Expensive for a Google phone.", links:[["Google Store","https://store.google.com/product/pixel_9_pro"],["Amazon","https://amazon.com/s?k=Google+Pixel+9+Pro"]]},
    { id:24, name:"OnePlus 13", price:699, match:84, emoji:"📱", specs:{Display:"6.82\" LTPO AMOLED 120Hz", Processor:"Snapdragon 8 Elite", RAM:"12GB", Storage:"256GB", Camera:"50MP Hasselblad triple", Battery:"6000mAh", OS:"Android 15", "5G":"Yes"}, why:"Biggest battery in flagship class. 100W charging fills in 26 minutes. Flagship chip at mid-range price.", tradeoff:"Camera not as refined as Samsung. Resale value lower.", links:[["OnePlus","https://oneplus.com"],["Amazon","https://amazon.com/s?k=OnePlus+13"]]},
    { id:25, name:"Samsung Galaxy Z Flip 7", price:1099, match:80, emoji:"📱", specs:{Display:"6.7\" AMOLED 120Hz foldable", Processor:"Snapdragon 8 Elite", RAM:"12GB", Storage:"256GB", Camera:"50MP dual", Battery:"3700mAh", OS:"Android 15", "5G":"Yes"}, why:"Best flip foldable. Compact when folded, full-size when open. Great cover display and premium build.", tradeoff:"Smaller battery due to foldable design. Very expensive.", links:[["Samsung","https://samsung.com"],["Amazon","https://amazon.com/s?k=Samsung+Galaxy+Z+Flip+7"]]},
  ],
  laptop: [
    // Budget laptops under $600
    { id:26, name:"Acer Chromebook Plus 514", price:349, match:68, emoji:"💻", specs:{Display:"14\" IPS FHD", Processor:"Intel Core i3-N305", RAM:"8GB", Storage:"128GB SSD", GPU:"Intel UHD", Battery:"Up to 10hrs", OS:"ChromeOS", Weight:"3.09 lbs"}, why:"Best for students who live in Google Docs and YouTube. Fast, lightweight, and incredibly affordable.", tradeoff:"ChromeOS won't run Windows apps. Not for gaming or video editing.", links:[["Acer","https://acer.com"],["Amazon","https://amazon.com/s?k=Acer+Chromebook+Plus+514"]]},
    { id:27, name:"Acer Aspire 5", price:499, match:74, emoji:"💻", specs:{Display:"15.6\" IPS FHD", Processor:"AMD Ryzen 5 7530U", RAM:"16GB", Storage:"512GB SSD", GPU:"AMD Radeon integrated", Battery:"Up to 8hrs", OS:"Windows 11", Weight:"3.97 lbs"}, why:"Best budget Windows laptop. Solid everyday performance for browsing, documents, coding, and light multitasking.", tradeoff:"No discrete GPU. Display not the brightest. Average battery.", links:[["Acer","https://acer.com"],["Amazon","https://amazon.com/s?k=Acer+Aspire+5"]]},
    { id:28, name:"Lenovo IdeaPad Slim 5", price:549, match:76, emoji:"💻", specs:{Display:"14\" IPS FHD", Processor:"AMD Ryzen 7 7730U", RAM:"16GB", Storage:"512GB SSD", GPU:"AMD Radeon integrated", Battery:"Up to 10hrs", OS:"Windows 11", Weight:"3.09 lbs"}, why:"Best student laptop under $600. Lightweight, good battery life, and enough power for coding and creative work.", tradeoff:"No discrete GPU. Display is just decent quality.", links:[["Lenovo","https://lenovo.com"],["Amazon","https://amazon.com/s?k=Lenovo+IdeaPad+Slim+5"]]},
    { id:29, name:"HP Laptop 15", price:429, match:68, emoji:"💻", specs:{Display:"15.6\" IPS FHD", Processor:"AMD Ryzen 5 5625U", RAM:"8GB", Storage:"256GB SSD", GPU:"AMD Radeon integrated", Battery:"Up to 8hrs", OS:"Windows 11", Weight:"3.75 lbs"}, why:"Reliable everyday laptop from HP. Good for basic school work, browsing, and video calls.", tradeoff:"Only 8GB RAM limits multitasking. Small 256GB storage.", links:[["HP","https://hp.com"],["Amazon","https://amazon.com/s?k=HP+Laptop+15"]]},
    { id:30, name:"ASUS VivoBook 16", price:499, match:72, emoji:"💻", specs:{Display:"16\" IPS FHD", Processor:"AMD Ryzen 5 7530U", RAM:"16GB", Storage:"512GB SSD", GPU:"AMD Radeon integrated", Battery:"Up to 9hrs", OS:"Windows 11", Weight:"3.97 lbs"}, why:"Best large-screen budget laptop. 16-inch display is great for studying and multitasking side by side.", tradeoff:"No discrete GPU. Average build quality.", links:[["ASUS","https://asus.com"],["Amazon","https://amazon.com/s?k=ASUS+VivoBook+16"]]},

    // Mid-range laptops $600-$1200
    { id:31, name:"ASUS Zenbook 14 OLED", price:799, match:83, emoji:"💻", specs:{Display:"14\" OLED 2.8K 120Hz", Processor:"AMD Ryzen 7 8700U", RAM:"16GB", Storage:"512GB SSD", GPU:"AMD Radeon 780M", Battery:"Up to 12hrs", OS:"Windows 11", Weight:"2.82 lbs"}, why:"Best OLED laptop under $800. Stunning display for content creators and students who care about screen quality.", tradeoff:"No discrete GPU. Not for heavy gaming.", links:[["ASUS","https://asus.com"],["Amazon","https://amazon.com/s?k=ASUS+Zenbook+14+OLED"]]},
    { id:32, name:"MacBook Air 13 M4", price:1099, match:95, emoji:"💻", specs:{Display:"13.6\" Liquid Retina", Processor:"Apple M4", RAM:"16GB", Storage:"256GB SSD", GPU:"10-core GPU", Battery:"Up to 18hrs", OS:"macOS Sequoia", Weight:"2.7 lbs"}, why:"Best all-around laptop for most people. Fanless, incredibly fast, and all-day battery. Perfect for students and professionals.", tradeoff:"Only 2 Thunderbolt ports. Not ideal for heavy gaming.", links:[["Apple","https://apple.com/macbook-air"],["Amazon","https://amazon.com/s?k=MacBook+Air+M4"]]},
    { id:33, name:"Dell XPS 13", price:999, match:87, emoji:"💻", specs:{Display:"13.4\" OLED touch", Processor:"Intel Core Ultra 7", RAM:"16GB", Storage:"512GB SSD", GPU:"Intel Arc", Battery:"Up to 12hrs", OS:"Windows 11", Weight:"2.73 lbs"}, why:"Best Windows ultrabook. Gorgeous OLED display and premium build quality in an ultra-compact package.", tradeoff:"Gets warm under load. Limited ports.", links:[["Dell","https://dell.com"],["Amazon","https://amazon.com/s?k=Dell+XPS+13"]]},
    { id:34, name:"Lenovo ThinkPad X1 Carbon", price:1349, match:86, emoji:"💻", specs:{Display:"14\" IPS 2.8K", Processor:"Intel Core Ultra 7", RAM:"16GB", Storage:"512GB SSD", GPU:"Intel Iris Xe", Battery:"Up to 15hrs", OS:"Windows 11 Pro", Weight:"2.48 lbs"}, why:"Best business laptop. Legendary keyboard, military-grade durability, and lightest in its class.", tradeoff:"No discrete GPU. Premium price for the specs.", links:[["Lenovo","https://lenovo.com"],["Amazon","https://amazon.com/s?k=Lenovo+ThinkPad+X1+Carbon"]]},
    { id:35, name:"Microsoft Surface Laptop 7", price:1299, match:84, emoji:"💻", specs:{Display:"13.8\" PixelSense 120Hz", Processor:"Snapdragon X Elite", RAM:"16GB", Storage:"512GB SSD", GPU:"Adreno X1", Battery:"Up to 20hrs", OS:"Windows 11", Weight:"2.96 lbs"}, why:"Best Windows laptop for battery life. Snapdragon X Elite gives MacBook-like endurance on Windows.", tradeoff:"ARM chip has some app compatibility issues. No discrete GPU.", links:[["Microsoft","https://microsoft.com/surface"],["Amazon","https://amazon.com/s?k=Microsoft+Surface+Laptop+7"]]},
    { id:36, name:"HP Spectre x360 14", price:1399, match:85, emoji:"💻", specs:{Display:"14\" OLED 2.8K touch 120Hz", Processor:"Intel Core Ultra 7", RAM:"16GB", Storage:"512GB SSD", GPU:"Intel Arc", Battery:"Up to 17hrs", OS:"Windows 11", Weight:"3.01 lbs"}, why:"Best 2-in-1 laptop. Folds completely flat for tablet use with a stunning OLED touchscreen and stylus support.", tradeoff:"Expensive. Heavier than non-convertible ultrabooks.", links:[["HP","https://hp.com"],["Amazon","https://amazon.com/s?k=HP+Spectre+x360+14"]]},

    // Gaming laptops
    { id:37, name:"HP Victus 15", price:749, match:80, emoji:"💻", specs:{Display:"15.6\" FHD 144Hz", Processor:"Intel Core i5-13420H", RAM:"16GB", Storage:"512GB SSD", GPU:"RTX 4050", Battery:"Up to 8hrs", OS:"Windows 11", Weight:"4.62 lbs"}, why:"Best budget gaming laptop. RTX 4050 handles most modern games at 1080p with a smooth 144Hz display.", tradeoff:"Build quality feels plasticky. Battery drains fast while gaming.", links:[["HP","https://hp.com"],["Amazon","https://amazon.com/s?k=HP+Victus+15"]]},
    { id:38, name:"MSI Katana 15", price:999, match:81, emoji:"💻", specs:{Display:"15.6\" FHD 144Hz", Processor:"Intel Core i7-13620H", RAM:"16GB", Storage:"512GB SSD", GPU:"RTX 5050", Battery:"Up to 6hrs", OS:"Windows 11", Weight:"5.07 lbs"}, why:"Latest RTX 50-series GPU under $1000. Good 1080p gaming performance with RGB keyboard.", tradeoff:"Dim display. Short battery life. Heavy build.", links:[["MSI","https://msi.com"],["Amazon","https://amazon.com/s?k=MSI+Katana+15"]]},
    { id:39, name:"ASUS TUF Gaming A15", price:849, match:82, emoji:"💻", specs:{Display:"15.6\" FHD 144Hz", Processor:"AMD Ryzen 7 7745HX", RAM:"16GB", Storage:"512GB SSD", GPU:"RTX 4060", Battery:"Up to 8hrs", OS:"Windows 11", Weight:"4.85 lbs"}, why:"Best value gaming laptop. RTX 4060 delivers great 1080p and 1440p gaming with military-grade durable build.", tradeoff:"Heavy and bulky. Display brightness could be better.", links:[["ASUS","https://asus.com"],["Amazon","https://amazon.com/s?k=ASUS+TUF+Gaming+A15"]]},
    { id:40, name:"Lenovo Legion 5 Gen 9", price:1199, match:85, emoji:"💻", specs:{Display:"15.6\" IPS 165Hz", Processor:"AMD Ryzen 7 8745H", RAM:"16GB", Storage:"512GB SSD", GPU:"RTX 4060", Battery:"Up to 8hrs", OS:"Windows 11", Weight:"5.4 lbs"}, why:"Best all-round gaming laptop. RTX 4060 with excellent thermals, good build quality, and great keyboard.", tradeoff:"Heavy. Battery drains fast during gaming.", links:[["Lenovo","https://lenovo.com"],["Amazon","https://amazon.com/s?k=Lenovo+Legion+5"]]},
    { id:41, name:"ASUS ROG Zephyrus G14", price:1499, match:91, emoji:"💻", specs:{Display:"14\" QHD OLED 165Hz", Processor:"AMD Ryzen 9 8945HS", RAM:"32GB", Storage:"1TB SSD", GPU:"RTX 4070", Battery:"Up to 10hrs", OS:"Windows 11", Weight:"3.31 lbs"}, why:"Best compact gaming laptop. RTX 4070 in a surprisingly portable 3.3 lb body with OLED display.", tradeoff:"Fan noise under load. Display could be brighter outdoors.", links:[["ASUS","https://rog.asus.com"],["Amazon","https://amazon.com/s?k=ASUS+ROG+Zephyrus+G14"]]},
    { id:42, name:"Razer Blade 14 2025", price:1999, match:88, emoji:"💻", specs:{Display:"14\" OLED 120Hz", Processor:"AMD Ryzen AI 9 365", RAM:"32GB", Storage:"1TB SSD", GPU:"RTX 5070", Battery:"Up to 11hrs", OS:"Windows 11", Weight:"3.59 lbs"}, why:"Best premium gaming laptop. RTX 5070 with OLED display in a sleek matte-black chassis that looks professional.", tradeoff:"Very expensive. Speakers could be better.", links:[["Razer","https://razer.com"],["Amazon","https://amazon.com/s?k=Razer+Blade+14+2025"]]},
    { id:43, name:"MacBook Pro 14 M4", price:1599, match:93, emoji:"💻", specs:{Display:"14.2\" Liquid Retina XDR", Processor:"Apple M4 Pro", RAM:"24GB", Storage:"512GB SSD", GPU:"20-core GPU", Battery:"Up to 22hrs", OS:"macOS Sequoia", Weight:"3.5 lbs"}, why:"Best laptop for video editing and creative work. M4 Pro handles 4K editing effortlessly with incredible battery life.", tradeoff:"Very expensive. Not for Windows-only software users.", links:[["Apple","https://apple.com/macbook-pro"],["Amazon","https://amazon.com/s?k=MacBook+Pro+14+M4"]]},
    { id:44, name:"Alienware 16 Aurora", price:1150, match:83, emoji:"💻", specs:{Display:"16\" QHD 120Hz", Processor:"Intel Core 7 240H", RAM:"16GB", Storage:"1TB SSD", GPU:"RTX 4050", Battery:"Up to 6hrs", OS:"Windows 11", Weight:"5.6 lbs"}, why:"Best large-screen budget gaming laptop. 16-inch QHD display with Alienware's premium build and reliability.", tradeoff:"Heavy at 5.6 lbs. Short battery life. RTX 4050 struggles at QHD.", links:[["Alienware","https://alienware.com"],["Amazon","https://amazon.com/s?k=Alienware+16+Aurora"]]},
  ]
}