export const QUESTIONS = {
  phone: [
    "Hey! 👋 What will you mainly use this phone for? (e.g. gaming, photography, social media, work, everyday use)",
    "Nice! Any must-have features? (e.g. great camera, long battery, compact size, 5G, fast charging)",
    "Almost there! Do you prefer any brand? Or are you open to all brands?",
  ],
  laptop: [
    "Hey! 👋 What will you mainly use this laptop for? (e.g. gaming, video editing, studying, programming, office work)",
    "Great! Any must-have features? (e.g. lightweight, long battery, powerful GPU, large screen, fast SSD)",
    "Almost there! Do you prefer Windows or macOS? Or no preference?",
  ]
}

export const DEVICES = {
  phone: [
    { id:1, name:"Samsung Galaxy S24", price:799, match:95, emoji:"📱", specs:{Display:"6.2\" AMOLED 120Hz", Processor:"Snapdragon 8 Gen 3", RAM:"8GB", Storage:"128GB", Camera:"50MP triple", Battery:"4000mAh", OS:"Android 14", "5G":"Yes"}, why:"Top-tier camera and blazing performance. The Snapdragon 8 Gen 3 handles anything you throw at it.", tradeoff:"Battery life is decent but not class-leading. Glass back scratches easily.", links:[["Amazon","https://amazon.com/s?k=Samsung+Galaxy+S24"],["Best Buy","https://bestbuy.com/site/searchpage.jsp?st=Samsung+Galaxy+S24"]]},
    { id:2, name:"iPhone 15", price:799, match:90, emoji:"📱", specs:{Display:"6.1\" Super Retina XDR", Processor:"A16 Bionic", RAM:"6GB", Storage:"128GB", Camera:"48MP dual", Battery:"3877mAh", OS:"iOS 17", "5G":"Yes"}, why:"Best-in-class software experience and camera quality. Great for Apple ecosystem users.", tradeoff:"No charger in box. USB-C but only USB 2 speeds.", links:[["Apple Store","https://apple.com/iphone-15"],["Amazon","https://amazon.com/s?k=iPhone+15"]]},
    { id:3, name:"Google Pixel 8a", price:499, match:88, emoji:"📱", specs:{Display:"6.1\" OLED 120Hz", Processor:"Google Tensor G3", RAM:"8GB", Storage:"128GB", Camera:"64MP dual", Battery:"4492mAh", OS:"Android 14", "5G":"Yes"}, why:"Incredible AI camera features and 7 years of updates. Best value in its price range.", tradeoff:"Tensor chip runs warm under heavy load. No telephoto lens.", links:[["Google Store","https://store.google.com/product/pixel_8a"],["Amazon","https://amazon.com/s?k=Google+Pixel+8a"]]},
    { id:4, name:"OnePlus 12", price:699, match:83, emoji:"📱", specs:{Display:"6.82\" LTPO AMOLED 120Hz", Processor:"Snapdragon 8 Gen 3", RAM:"12GB", Storage:"256GB", Camera:"50MP Hasselblad triple", Battery:"5400mAh", OS:"Android 14", "5G":"Yes"}, why:"Massive battery, 100W fast charging, and flagship chip for less money than Samsung.", tradeoff:"Camera software less refined. OxygenOS has more bloat now.", links:[["OnePlus","https://oneplus.com/global/12"],["Amazon","https://amazon.com/s?k=OnePlus+12"]]},
    { id:5, name:"Motorola Edge 50 Pro", price:399, match:78, emoji:"📱", specs:{Display:"6.7\" pOLED 144Hz", Processor:"Snapdragon 7s Gen 2", RAM:"12GB", Storage:"256GB", Camera:"50MP triple", Battery:"4500mAh", OS:"Android 14", "5G":"Yes"}, why:"Best budget option with a flagship-grade display and 68W fast charging.", tradeoff:"Mid-range chip may lag on heavy gaming or video editing.", links:[["Motorola","https://motorola.com"],["Amazon","https://amazon.com/s?k=Motorola+Edge+50+Pro"]]},
    { id:6, name:"Samsung Galaxy A55", price:449, match:74, emoji:"📱", specs:{Display:"6.6\" Super AMOLED 120Hz", Processor:"Exynos 1480", RAM:"8GB", Storage:"128GB", Camera:"50MP triple", Battery:"5000mAh", OS:"Android 14", "5G":"Yes"}, why:"Solid mid-ranger with great display and 4 years of Samsung software support.", tradeoff:"Exynos chip is noticeably slower than Snapdragon equivalents.", links:[["Samsung","https://samsung.com"],["Amazon","https://amazon.com/s?k=Samsung+Galaxy+A55"]]},
  ],
  laptop: [
    { id:7, name:"MacBook Air M3", price:1099, match:93, emoji:"💻", specs:{Display:"13.6\" Liquid Retina", Processor:"Apple M3", RAM:"8GB", Storage:"256GB SSD", GPU:"10-core", Battery:"Up to 18hrs", OS:"macOS Sonoma", Weight:"2.7 lbs"}, why:"The best all-around laptop for most users. Fanless, incredibly fast, and all-day battery.", tradeoff:"Only 2 USB-C ports. 8GB RAM feels tight for heavy video editing.", links:[["Apple Store","https://apple.com/macbook-air"],["Amazon","https://amazon.com/s?k=MacBook+Air+M3"]]},
    { id:8, name:"Dell XPS 13", price:999, match:87, emoji:"💻", specs:{Display:"13.4\" OLED touch", Processor:"Intel Core Ultra 7", RAM:"16GB", Storage:"512GB SSD", GPU:"Intel Arc", Battery:"Up to 12hrs", OS:"Windows 11", Weight:"2.73 lbs"}, why:"Premium Windows ultrabook with a gorgeous OLED display. Great for productivity and travel.", tradeoff:"Gets warm under load. Webcam position awkward on older models.", links:[["Dell","https://dell.com"],["Amazon","https://amazon.com/s?k=Dell+XPS+13"]]},
    { id:9, name:"ASUS ROG Zephyrus G14", price:1499, match:82, emoji:"💻", specs:{Display:"14\" QHD 165Hz", Processor:"AMD Ryzen 9 8945HS", RAM:"16GB", Storage:"1TB SSD", GPU:"RTX 4070", Battery:"Up to 10hrs", OS:"Windows 11", Weight:"3.64 lbs"}, why:"Powerful gaming and creative work in a compact body. RTX 4070 handles 4K editing and AAA games.", tradeoff:"Fan noise under load. Display could be brighter.", links:[["ASUS","https://rog.asus.com"],["Amazon","https://amazon.com/s?k=ASUS+ROG+Zephyrus+G14"]]},
    { id:10, name:"Lenovo ThinkPad X1 Carbon", price:1349, match:79, emoji:"💻", specs:{Display:"14\" IPS 2.8K", Processor:"Intel Core Ultra 7", RAM:"16GB", Storage:"512GB SSD", GPU:"Intel Iris Xe", Battery:"Up to 15hrs", OS:"Windows 11 Pro", Weight:"2.48 lbs"}, why:"Best business laptop. Legendary keyboard, lightest in class, military-grade durability.", tradeoff:"No discrete GPU. Expensive for specs vs consumer laptops.", links:[["Lenovo","https://lenovo.com"],["Amazon","https://amazon.com/s?k=Lenovo+ThinkPad+X1+Carbon"]]},
    { id:11, name:"Acer Aspire 5", price:549, match:71, emoji:"💻", specs:{Display:"15.6\" IPS FHD", Processor:"AMD Ryzen 5 7530U", RAM:"16GB", Storage:"512GB SSD", GPU:"AMD Radeon", Battery:"Up to 8hrs", OS:"Windows 11", Weight:"3.97 lbs"}, why:"Best budget laptop for students. Solid build and decent performance for everyday tasks.", tradeoff:"Display isn't the brightest. Battery life is mediocre. Not for gaming.", links:[["Acer","https://acer.com"],["Amazon","https://amazon.com/s?k=Acer+Aspire+5"]]},
  ]
}